/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function DarkFantasyModel(props) {
  const { nodes, materials } = useGLTF('/assets/dark-fantasy-transformed.glb')
  return (
    <group {...props} dispose={null} >
      <group scale={0.37}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['ITC531727_Dark_Fantasy_Chocofills_USA_75g_V42_R1_ard-node'].geometry}
        material={materials.blinn1}
        position={[19.178, -2.9, 19.88]}
        rotation={[0,3,0]}
        scale={0.1}
      />
    </group>

    </group>
  )
}

useGLTF.preload('/assets/dark-fantasy-transformed.glb')