/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export function LogoModel(props) {
  const { nodes, materials } = useGLTF('/assets/logo-transformed.glb')
  return (
    <group {...props} dispose={null} scale={0.025} position={[0, 0.1, 0]}>
      <group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_2001.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_2001_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_2001_2.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_2001_3.geometry}
          material={materials['Material.003']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/logo-transformed.glb')


